export const SET_LOGIN_STATUS_LOADING = 'SET_LOGIN_STATUS_LOADING'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_IS_LOGGED = 'SET_IS_LOGGED'
export const RESET_LOGIN_ERRORS = 'RESET_LOGIN_ERRORS'
export const UPDATE_LOGIN_DATA = 'UPDATE_LOGIN_DATA'
export const RESET_LOGIN_REDUCER = 'RESET_LOGIN_REDUCER'

export const TRY_LOGIN = 'TRY_LOGIN'
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'
export const TRY_UPLOAD_IMAGE = "TRY_UPLOAD_IMAGE"
export const SET_AVATAR = 'SET_AVATAR'
export const SET_COVER = 'SET_COVER'
///TEMPORARY REDUCER


export const CHANGE_MODAL_STATUS = 'CHANGE_MODAL_STATUS'
export const RESET_MODAL_STATUS = 'RESET_MODAL_STATUS'
export const RESET_TEMPORARY_REDUCER = 'RESET_TEMPORARY_REDUCER'
export const SET_ANUNT_ID = 'SET_ANUNT_ID'
export const TRY_IMAGE_UPLOAD = 'TRY_IMAGE_UPLOAD'
export const SET_IMAGE_UPLOAD_LOADING = 'SET_IMAGE_UPLOAD_LOADING'
export const SET_SELECTED_FILE = 'SET_SELECTED_FILE'
export const SET_IMAGE_TYPE = 'SET_IMAGE_TYPE'
export const SET_BLOB_AVATAR = 'SET_BLOB_AVATAR'
export const SET_BLOB_COVER = 'SET_BLOB_COVER'
export const RESET_BLOB = 'RESET_BLOB'


//ANUNTURI REDUCER

export const SET_ANUNTURI_LOADING = 'SET_ANUNTURI_LOADING'
export const SET_ANUNTURI = 'SET_ANUNTURI'
export const GET_ANUNTURI = 'GET_ANUNTURI'


//SIGNUP REDUCER

export const TRY_SIGNUP = 'TRY_SIGNUP'
export const SET_SIGNUP_STATUS_LOADING = 'SET_SIGNUP_STATUS_LOADING'
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR'
export const RESET_SIGNUP_ERRORS = 'RESET_SIGNUP_ERRORS'
export const UPDATE_SIGNUP_DATA = 'UPDATE_SIGNUP_DATA'
export const RESET_SIGNUP_REDUCER = 'RESET_SIGNUP_REDUCER'

