// temporaryReducer

export const RESET_TEMPORARY_REDUCER = 'RESET_TEMPORARY_REDUCER'
export const SET_TEMPORARY_VALUE = 'SET_TEMPORARY_VALUE'
export const TRY_RECOVER_PASSWORD = 'TRY_RECOVER_PASSWORD'
export const TRY_LOGIN = 'TRY_LOGIN'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const TRY_RESET_PASSWORD = 'TRY_RESET_PASSWORD'
export const CHECK_HASH_RESET_PASSWORD = 'CHECK_HASH_RESET_PASSWORD'
export const REMOVE_TEMPORARY_ERRORS = 'REMOVE_TEMPORARY_ERRORS'
export const CHANGE_TAB = 'CHANGE_TAB'

// notificationReducer

export const RESET_NOTIFICATION_REDUCER = 'RESET_NOTIFICATION_REDUCER'
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
export const SEND_PERSISTENT_NOTIFICATION = 'SEND_PERSISTENT_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

// loginReducer

export const TRY_FACEBOOK_LOGIN = 'TRY_FACEBOOK_LOGIN'
export const TRY_GOOGLE_LOGIN = 'TRY_GOOGLE_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const SET_LOGIN_VALUE = 'SET_LOGIN_VALUE'
export const RESET_LOGIN_REDUCER = 'RESET_LOGIN_REDUCER'
export const DO_LOGOUT_CLEANUP = 'DO_LOGOUT_CLEANUP'

// registerReducer

export const RESET_REGISTER_REDUCER = 'RESET_REGISTER_REDUCER'
export const SET_REGISTER_VALUE = 'SET_REGISTER_VALUE'
export const TRY_REGISTER = 'TRY_REGISTER'

// settingsReducer

export const RESET_SETTINGS_REDUCER = 'RESET_SETTINGS_REDUCER'
export const SET_SETTINGS_VALUE = 'SET_SETTINGS_VALUE'

// updateProfile

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const RESET_UPDATE_PROFILE_REDUCER = 'RESET_UPDATE_PROFILE_REDUCER'
export const SET_UPDATE_PROFILE_VALUE = 'SET_UPDATE_PROFILE_VALUE'
export const TRY_SET_UPDATE_PROFILE_VALUE = 'TRY_SET_UPDATE_PROFILE_VALUE'
export const SET_OPEN_EDIT_PROFILE_MODAL = 'SET_OPEN_EDIT_PROFILE_MODAL'
export const TRY_CHANGE_AVATAR = 'TRY_CHANGE_AVATAR'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

// scheduceReducer

export const RESET_SCHEDULE_REDUCER = 'RESET_SCHEDULE_REDUCER'
export const SET_SCHEDULE_VALUES = 'SET_SCHEDULE_VALUES'
export const SET_SCHEDULE_TEMP_VALUE = 'SET_SCHEDULE_TEMP_VALUE'
export const RESET_SCHEDULE_TEMP_VALUES = 'RESET_SCHEDULE_TEMP_VALUES'
export const SET_SCHEDULE_FROM_SERVER = 'SET_SCHEDULE_FROM_SERVER'

// uploadVehicleReducer

export const RESET_UPLOAD_VEHICLES = 'RESET_UPLOAD_VEHICLES'
export const SET_UPLOAD_VEHICLES_VALUE = 'SET_UPLOAD_VEHICLES_VALUE'
export const TRY_UPLOAD_VEHICLE = 'TRY_UPLOAD_VEHICLE'
export const TRY_DELETE_VEHICLE = 'TRY_DELETE_VEHICLE'

// myVehicleReducer

export const RESET_MY_VEHICLES = 'RESET_MY_VEHICLES'
export const SET_MY_VEHICLES = 'SET_MY_VEHICLES'
export const CHANGE_VEHICLE_STATUS = 'CHANGE_VEHICLE_STATUS'
export const GO_OFFLINE_FROM_WORK = 'GO_OFFLINE_FROM_WORK'

// couriersReducer

export const RESET_COURIERS_REDUCER = 'RESET_COURIERS_REDUCER'
export const SET_MY_COURIERS = 'SET_MY_COURIERS'

// MASTER

export const START_SYNC_APP = 'START_SYNC_APP'
export const STOP_SYNC_APP = 'STOP_SYNC_APP'

// nav

export const SET_MY_POSITION = 'SET_MY_POSITION'

// pricesReducer

export const RESET_PRICES_REDUCER = 'RESET_PRICES_REDUCER'
export const SET_PRICES_VALUES = 'SET_PRICES_VALUES'
export const RESET_PRICES_TEMP_VALUES = 'RESET_PRICES_TEMP_VALUES'
export const SET_PRICES_TEMP_VALUE = 'SET_PRICES_TEMP_VALUE'
export const SET_PRICES_FROM_SERVER = 'SET_PRICES_FROM_SERVER'

// sendPack

export const TRY_SEND_PACK = 'TRY_SEND_PACK'
export const RESET_MY_PACKS = 'RESET_MY_PACKS'
export const SET_MY_PACKS = 'SET_MY_PACKS'
export const CHANGE_PACK_STATUS = 'CHANGE_PACK_STATUS'
export const TRY_CANCEL_PACK = 'TRY_CANCEL_PACK'
export const TRY_RATE_DELIVERY = 'TRY_RATE_DELIVERY'
export const TRY_ACCEPT_REQUEST_PACK = 'TRY_ACCEPT_REQUEST_PACK'
export const TRY_DECLINE_REQUEST_PACK = 'TRY_DECLINE_REQUEST_PACK'
export const TRY_REFUND_REQUEST_PACK = 'TRY_REFUND_REQUEST_PACK'
export const CHANGE_PACK_RATED = 'CHANGE_PACK_RATED'
export const TRY_PICKED_UP = 'TRY_PICKED_UP'
