//images

export const bannerHome = require('./BANNER.svg')
export const xIcon = require('./x.svg')
export const testImage = require('./test.jpg')
export const heartIcon = require('./heart.svg')
export const shareIcon = require('./share.svg')
export const nixxLogo = require('./nixxLogo.svg')
export const nixxRedLogo = require('./nixxRedLogo.svg')


//icons
export const menuIcon = require('./Icons/menuIcon.svg')
export const animaleIcon = require('./Icons/animaleIcon.svg')
export const autoMotoIcon = require('./Icons/autoMotoIcon.svg')
export const casaIcon = require('./Icons/casaIcon.svg')
export const copilIcon = require('./Icons/copilIcon.svg')
export const diverseIcon = require('./Icons/diverseIcon.svg')
export const electroniceIcon = require('./Icons/electroniceIcon.svg')
export const imobiliareIcon = require('./Icons/imobiliareIcon.svg')
export const matrimonialeIcon = require('./Icons/matrimonialeIcon.svg')
export const modaIcon = require('./Icons/modaIcon.svg')
export const muncaIcon = require('./Icons/muncaIcon.svg')
export const serviciiIcon = require('./Icons/serviciiIcon.svg')
export const sportIcon = require('./Icons/sportIcon.svg')
export const userIcon = require('./Icons/userIcon.svg')
export const passwordIcon = require('./Icons/passwordIcon.svg')
export const cameraIcon = require('./Icons/cameraIcon.svg')
export const profileBackIcon = require('./Icons/profileBackIcon.svg')
export const phoneIcon = require('./Icons/phoneIcon.svg')
export const emailIcon = require('./Icons/emailIcon.svg')
export const editIcon = require('./Icons/editIcon.svg')
export const searchIcon = require('./Icons/seachIcon.svg')
export const aboutUser = require('./aboutUser.svg')
export const badgeMenuIcon = require('./Icons/profileBadgeMenuIcon.svg')
export const profileIcon = require('./Icons/profileIcon.svg')
export const anunturiIcon = require('./Icons/anunturiIcon.svg')

//illustrations
export const loginIllustration = require('./Illustrations/login.svg')
export const error404 = require('./Illustrations/error404.svg')
export const contactIllustration = require('./Illustrations/contactIllustration.svg')
export const signupIllustration = require('./Illustrations/signupIllustration.svg')