package com.example.foodappv3.l3_model;

public class FoodData //clasa utilitara pt a usura pre-inserarea in db
{
    public static Food[] FoodRows()
    {
        return new Food[]
                {
                        new Food("Falafel","https://media.realitatea.net/multimedia/image/201910/w728/falafel_reteta_turceasca_69491300.jpg","40 minute","usor","250 g naut boabe\n" + "\n" + "1 legatura patrunjel tocat\n" + "\n" + "4 catei de usturoi\n" + "\n" + "1 ceapa\n" + "\n" + "sare, dupa gust\n" + "\n" + "2 linguri faina\n" + "\n" + "chimion\n" + "\n" + "coriandru\n" + "\n" + "boia dulce\n" + "\n" + "\n" + "\n" + "Nautul se lasa la inmuiat in apa rece timp de 8 ore. Dupa aceea, se spala bine, se pune in blender si se marunteste pana devine o pasta grunjoasa.\n" + "\n" + "Patrunjelul si ceapa se taie marunt, ustoroiul se piseaza si apoi toate trei ingredientele se adauga in compozitie. Se adauga si condimentele.\n" + "\n" + "Falafel rețeta turcească. Se presara cele 2 linguri de faina in ploaie, amestecand bine pana la omogenizare si se adauga putina sare, dupa gust.\n" + "\n" + "Cu mainile, se modelează bilute din compozitia obtinuta.\n" + "\n" + "Chiftelutele se prajesc sau se pun la cuptor, intr-o tava tapetata cu hartie de copt.\n" + "\n" + "Falafel rețeta turcească.  Sunt gata atunci cand le vezi ca s-au rumenit, nu trebuie lasate foarte mult, ca sa nu se usuce excesiv.\n" + "\n" + "Etapa de inmuiere a nautului este extrem de importanta, pentru ca in prezenta apei, aceast aliment se hidrateaza si isi activeaza proprietatile benefice.\n" + "\n" + "Vei vedea ca nautul care se lasa la inmuiat peste noapte se va umfla foarte mult, de aceea trebuie sa pui apa in cantitate cel putin dubla fata de naut."),
                        new Food("Paste Carbonara","https://www.retetepractice.ro/wp-content/uploads/2017/08/Paste-Carbonara-reteta-originala.jpg", "20 minute", "usor","400 g spaghete\n" + "\n" + "200 g guanciale (alternativ pancetta/bacon)\n" + "\n" + "4 galbenusuri\n" + "\n" + "75 g branza pecorino\n" + "\n" + "sare\n" + "\n" + "piper\n" + "\n" + "\n" +"\n"+ "Pune apa la fiert intr-o cratita incapatoare, cu o lingurita de sare. Cand apa incepe sa fiarba, pune si pastele la fiert pentru 4-5 minute.\n" + "\n" + "In rastimp insa, pana sa fiarba apa, taie guanciale cubulete (daca ai acces la acest tip de preparat, daca nu pancetta sau bacon).\n" + "\n" + "Bate galbenusurile cu 40-50 g de branza pecorino (din nou, ideal. Daca nu gasesti, poti folosi si parmezan). Frige baconul in tigaie fara ulei, pana cand devine crocant si grasimea se topeste.\n" + "\n" + "Cand pastele au fiert 4-5 minute, scoate-le cu un cleste si pune-le direct peste bacon. Agita pastele putin pentru un minut, apoi adauga ~o cana de apa de la paste.\n" + "\n" + "Lasa pastele carbonara sa se raceasca un minut, apoi adauga amestecul de galbenusuri si branza, amestecand energic pentru a evita coagularea galbenusurilor.\n" + "\n" + "Pune pastele la foc pentru inca 30-60 secunde, apoi serveste fiecare portie de paste carbonara cu putina branza pecorino rasa deasupra si putin piper proaspat macinat."),
                        new Food("Ciorba de Burta","https://depozitulderetete.ro/wp-content/uploads/2015/05/ciorba-de-burta-01.jpg","80 minute","mediu","1 kg Burta de vita \n" + "\n" + "4 litri Apa \n" + "\n" + "1.2 kg Oase de vita (genunchi de vita)\n" + "\n" + "200 grame Telina (un sfert de telina mai mare)\n" + "\n" + "135 grame Morcovi (1 buc.)\n" + "\n" + "100 grame Patrunjel radacina (1 buc.) sau pastarnac\n" + "\n" + "grame Piper negru (20 boabe)\n" + "\n" + "2 buc. Foi de dafin \n" + "\n" + "2 buc. Galbenus de ou \n" + "\n" + "2 linguri Otet din vin \n" + "\n" + "1 lingurita Sare de bucatarie \n" + "\n" + "\n" + "\n" + "Curata burta de vita de toate pielitele si resturi, pana cand burta ramane perfect alba si perfect curata. Poti folosi sare sau o perie.\n" + "\n" + "Curata si spala genunchiul de vita foarte bine.\n" + "\n" + "Curata legumele si taie-le cuburi mari.\n" + "\n" + "Pune burta de vita si genunchiul la fiert, in 4 litri de apa rece, cu o lingurita rasa de sare. Adauga si legumele.\n" + "\n" + "Curata spuma care apare deasupra apei.\n" + "\n" + "Poti fierbe la presiune cam o ora sau simplu, la foc mediu in jur de doua ore. Burta este fiarta cand este moale si se taie usor.\n" + "\n" + "Scoate burta din oala, lasa-o sa se raceasca usor apoi taie in forma de taitei mai grosi, la fel si carnea de pe picior.\n" + "\n" + "Strecoara zeama in care au fiert, apoi pune-o din nou pe foc si lasa sa mai dea cateva clocote, apoi ia de pe foc.\n" + "\n" + "Pune burta de vita si carnea taiata inapoi in oala dar si legumele fierte.\n" + "\n" + "Separa galbenusurile de albusuri, amesteca-le bine cu cele doua linguri de otet si amesteca cate putin cu ciorba din oala.\n" + "\n" + "Daca este necesar, mai adauga sare si otet (in functie de gust) si gata cu ciorba de burta.\n" + "\n" + "Ciorba de burta in reteta originala se consuma ca atare insa dressingul de smantana si usturoi o face si mai buna."),
                        new Food("Desert cu Oreo si Mascarpone","https://www.teoskitchen.ro/wp-content/uploads/2018/08/desert-cu-oreo-si-mascarpone-desert-la-pahar-6.jpg","10 minute","usor","180g biscuiti Sondey Neo\n" + "\n" + "80g zahar pudra vanilat Castello\n" + "\n" + "250g mascarpone Lovilio\n" + "\n" + "200g crema de smantana natur Pilos\n" + "\n" + "200ml smantana dulce pentru frisca Pilos\n" + "\n" + "½ lingurita esenta de vanilie Castello\n" + "\n" + "\n" + "\n" + "Procedura este foarte simpla: jumatate din biscutii ii dam prin blender (cu tot cu crema din interior) pana sunt fin maruntiti. \n" + "\n" + "Cealalta jumatate ii rupem in bucati mari.\n" + "\n" + "Pentru crema, pur si simplu punem intr-un bol toate ingredientele: mascarpone, crema de smantana, frisca lichida, zaharul pudra, esenta de vanilie. \n" + "\n" + "Important este ca toate ingredientele sa fie foarte reci, de la frigider, mai ales smantana dulce. Pentru a fi siguri ca frisca se bate bine,  tineti smantana dulce 15 minute la congelator inainte de a o pune in bol alaturi de restul ingredientelor.\n" + "\n" + "Amestecam totul cu mixerul 5-6 minute sau pana avem o crema densa. In crema obtinuta, punem biscutiii rupti in bucati mari.\n" + "\n" + "In fiecare pahar (folosim pahare dde 150-200ml) punem cate o lingura plina de biscuiti macinati fin, apoi crema, apoi inca un strat de biscuiti macinati, astfel incat sa epuizam biscuitii si crema. Dam desertul la rece 2-3 ore inainte de servire."),
                        new Food("Cozonac cu Mac","https://retete.unica.ro/wp-content/uploads/2013/11/cozonac-mac.jpg","70 minute", "mediu","275 g făină\n" + " \n" + "100 g unt\n" + " \n" + "70 g zahăr\n" + " \n" + "50 ml lapte\n" + " \n" + "8 g drojdie proaspătă\n" + " \n" + "2 ouă\n" + "\n" + " \n" + "Pentru umplutură\n" + " \n" + "250 g mac\n" + " \n" + "2 ouă\n" + " \n" + "30 g unt\n" + " \n" + "80 g zahăr\n" + " \n" + "20 g zahăr vanilat\n" + " \n" + "40 g stafide\n" + " \n" + "50 g fructe confiate\n" + " \n" + " \n" + " \n" + "\n" + "Se prepara umplutura pentru care macul se pune într-o craticioara, se acopera cu apa si se fierbe 5 minute din momentul în care da în clocot. \n" + "\n" + "Apoi, se trage de pe foc si se lasa o ora în apa în care a fiert. Se scurge bine.\n" + "\n" + "Pentru aluat, drojdia se desface în laptele calduţ si se amesteca cu ouale batute. Se toarna acest amestec în golul facut în faina si se încorporeaza foarte bine. \n" + "\n" + "Apoi, se adauga untul moale şi zaharul si se framânta din nou pâna la încorporarea completa. Se lasa o ora sa creasca.\n" + "\n" + "Macul se mixeaza cu untul, zaharul, zaharul vanilinat, un ou întreg si un albus. \n" + "\n" + "Galbenusul se pastreaza pentru uns. Se adauga stafidele si fructele confiate taiate marunt.\n" + "\n" + "Se întinde aluatul într-o foaie de aproximativ 30-40 cm si se umple cu compoziţia din mac. Se ruleaza si se asaza în tava. \n" + "\n" + "Se lasa asa înca 30 de minute, apoi se coace 40 de minute.")
                };
    }
}
