import {makeStyles} from '@material-ui/core/styles'

const useClasses = makeStyles(theme =>({
    blackBar:{
        display: 'flex',
        alignItems: 'center',
        width: 'calc(100% - 30px)',
        margin:'0 auto',
        backgroundColor: '#262626',
        borderRadius: '8px',
        minHeight: '40px',
        marginTop: '15px',
        padding: '5px',
        position: 'relative',
        height: '40px',
    },
    adaugaAnunt:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: '7px',
        height: '100%',
        border: '2px solid #f35',
        color: 'white',
        fontWeight: 700,
        fontSize: '7pt'
    },
    selectOras:{
            backgroundColor: 'white',
            width: '100px',
            
    },
    selectContainer:{
        '& :first-child':{
            borderRight: '1px solid rgba(42,42,42,.2)'
        },
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: 'calc(100% - 155px)',
        marginRight: '5px',
        marginLeft: '35px',
        padding:'5px',
        height: '100%',
        borderRadius: '4px',
        background:'white',
        boxShadow: '0px 1px 3px rgba(0,0,0,0.05), 0px 1px 2px rgba(0,0,0,0.1)',
    },
    selectItem:{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        fontSize: '9pt',
        fontWeight: 800,
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    inputContainer:{
        position: 'absolute',
        backgroundColor: 'white',
        display: 'flex',
        flexDirection: 'row',
        padding: '5px',
        height: '100%',
        borderRadius: '4px',
        marginRight: '5px',
        minWidth: '30px',
        width: '30px',
        justifyContent: 'space-between',
        alignItems: 'center',
        transition: 'width .5s',
        webkitTransition: 'width .5s',
        height: 'calc(100% - 10px)',
        zIndex: '10',
    },
    inputBar:{
        width: '0px',
        height: '100%',
        backgroundColor: 'white',
        transition: 'width .5s',
        webkitTransition: 'width .5s',
    },
    expandedInput:{
        width: 'calc(100% - 30px)',
        
    },
    expandedInputContainer:{
        width:'calc(100% - 10px)',
        
        transition: 'width .5s',
        webkitTransition: 'width .5s',
        
    },
    anuntContainer:{
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        borderRadius: '8px',
        background: 'white',
        boxShadow: '0px 1px 3px rgba(0,0,0,0.05), 0px 1px 2px rgba(0,0,0,0.1)',
        padding: '10px',
        marginBottom:'10px',
    },
    modal: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        
      },
    paper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        // minHeight: 'calc(100% - 30px)', 
        maxHeight: '345px', 
        width: 'calc(100% - 30px)',
        height: '100%',
        // backgroundColor: 'white',
        border: '2px solid #000',
        border:'0px',
        borderRadius: '8px',
        boxShadow: theme.shadows[5],
        // padding: '15px',
    },
    selectJudeteContainer:{
        touchAction:'none',
    },
    backdropModal:{
        zIndex: '-1',
        position: 'fixed',
        right: '0px',
        bottom: '0px',
        top: '0px',
        left: '0px',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        WebkitTapHighlightColor: 'transparent',
        touchAction: 'none',
    },

    selectList:{
        display: 'flex',
        flexDirection: 'column',
        width:'100%',
        padding : '0px',
        overflowX: 'auto',
        marginTop: '25px',
    },
    selectListElement:{
        display: 'flex',
        alignItems: 'center',
        height: '35px',
        width: '100%',
        fontWeight: 900,
        fontSize: '12pt',
        paddingLeft: '20px',
        borderBottom: '1px solid rgba(42,42,42,.1)',
        fontStyle: 'italic',
        backgroundColor:'white'
    },
    modalDescriereText:{
        marginTop: '15px',
        overflowY: 'auto',
        height: '300px',
        fontSize: '9.5pt',
        width: '100%',
    },
    selectListInput:{
        position: 'absolute',
            top: 0,
            left: 0,
        width: '100%',
        // borderTopRightRadius: '8px',
        // borderTopLeftRadius: '8px',
        '& input ':{
            // borderTopRightRadius: '8px',
            // borderTopLeftRadius: '8px',
            paddingLeft: '20px',
            backgroundColor: '#262626',
            padding: '10px',
            color: 'white',
            width: '100%',
            fontWeight: 500,
            textAlign: 'center',
        },
    },
    selectListElementSelected:{
        display: 'flex',
        alignItems: 'center',
        height: '35px',
        width: '100%',
        fontWeight: 900,
        fontSize: '12pt',
        paddingLeft: '20px',
        borderBottom: '1px solid rgba(42,42,42,.1)',
        fontStyle: 'italic',
        color:'white',
        backgroundColor: '#f35',
        borderRadius: '4px',
    },
    selectListButtons:{
        width: '100%',
        background: 'white',
        minHeight: '45px',
        height: '45px',
        display: 'flex',
        alignItems: 'center',
        borderBottomLeftRadius: '8px',
        borderBottomRightRadius: '8px',
        '& > :first-child':{
            fontWeight: 900,
            color:'white',
            fontSize: '7pt',
            marginRight: '5px',
            marginLeft: 'auto',
            background: '#262626 !important',
            width: 'calc(50% - 25px)',
            height: '30px',
        },
        '& > :last-child':{
            height: '30px',
            fontWeight: 900,
            color:'white',
            fontSize: '7pt',
            marginLeft: '5px',
            marginRight: 'auto',
            background: '#f35 !important',
            width: 'calc(50% - 25px)',
        }
    },
}))

export default useClasses